ciiu_agregacion = {"01":("Agricultura, ganadería, caza y actividades de servicios conexas","Agricultura, ganadería, silvicultura y pesca", "Agricultura, ganadería, silvicultura y pesca"),
"02":("Silvicultura y extracción de madera", "Agricultura, ganadería, silvicultura y pesca"),
"03":("Pesca y acuicultura", "Agricultura, ganadería, silvicultura y pesca"),
"05":("Extracción de carbón de piedra y lignito", "Explotación de minas y canteras"),
"06":("Extracción de petróleo crudo y gas natural", "Explotación de minas y canteras"),
"07":("Extracción de minerales metalíferos", "Explotación de minas y canteras"),
"08":("Explotación de otras minas y canteras", "Explotación de minas y canteras"),
"09":("Actividades de servicios de apoyo para la explotación de minas y canteras", "Explotación de minas y canteras"),
"10":("Elaboración de productos alimenticios", "Industrias manufactureras"),
"11":("Elaboración de bebidas", "Industrias manufactureras"),
"12":("Elaboración de productos de tabaco", "Industrias manufactureras"),
"13":("Fabricación de productos textiles", "Industrias manufactureras"),
"14":("Fabricación de prendas de vestir", "Industrias manufactureras"),
"15":("Fabricación de productos de cuero y productos conexos", "Industrias manufactureras"),
"16":("Producción de madera y fabricación de productos de madera y corcho, excepto muebles; fabricación de artículos de paja y de materiales trenzables", "Industrias manufactureras"),
"17":("Fabricación de papel y de productos de papel", "Industrias manufactureras"),
"18":("Impresión y reproducción de grabaciones", "Industrias manufactureras"),
"19":("Fabricación de coque y productos de la refinación del petróleo", "Industrias manufactureras"),
"20":("Fabricación de sustancias y productos químicos", "Industrias manufactureras"),
"21":("Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico ", "Industrias manufactureras"),
"22":("Fabricación de productos de caucho y de plástico", "Industrias manufactureras"),
"23":("Fabricación de otros productos minerales no metálicos", "Industrias manufactureras"),
"24":("Fabricación de metales comunes", "Industrias manufactureras"),
"25":("Fabricación de productos elaborados de metal, excepto maquinaria y equipo", "Industrias manufactureras"),
"26":("Fabricación de productos de informática, de electrónica y de óptica", "Industrias manufactureras"),
"27":("Fabricación de equipo eléctrico", "Industrias manufactureras"),
"28":("Fabricación de maquinaria y equipo n.c.p.", "Industrias manufactureras"),
"29":("Fabricación de vehículos automotores, remolques y semirremolques", "Industrias manufactureras"),
"30":("Fabricación de otro equipo de transporte", "Industrias manufactureras"),
"31":("Fabricación de muebles", "Industrias manufactureras"),
"32":("Otras industrias manufactureras", "Industrias manufactureras"),
"33":("Reparación e instalación de maquinaria y equipo", "Industrias manufactureras"),
"35":("Suministro de electricidad, gas, vapor y aire acondicionado", "Suministro de electricidad, gas, vapor y aire acondicionado"),
"36":("Captación, tratamiento y distribución de agua", "Suministro de agua; evacuación de aguas residuales, gestión de desechos y descontaminación"),
"37":("Evacuación de aguas residuales", "Suministro de agua; evacuación de aguas residuales, gestión de desechos y descontaminación"),
"38":("Recogida, tratamiento y eliminación de desechos; recuperación de materiales", "Suministro de agua; evacuación de aguas residuales, gestión de desechos y descontaminación"),
"39":("Actividades de descontaminación y otros servicios de gestión de desechos", "Suministro de agua; evacuación de aguas residuales, gestión de desechos y descontaminación"),
"41":("Construcción de edificios", "Construcción"),
"42":("Obras de ingeniería civil", "Construcción"),
"43":("Actividades especializadas de construcción", "Construcción"),
"45":("Comercio al por mayor y al por menor y reparación de vehículos automotores y motocicletas", "Comercio al por mayor y al por menor;reparación de vehículos automotores y motocicletas"),
"46":("Comercio al por mayor, excepto el de vehículos automotores y motocicletas", "Comercio al por mayor y al por menor;reparación de vehículos automotores y motocicletas"),
"47":("Comercio al por menor, excepto el de vehículos automotores y motocicletas", "Comercio al por mayor y al por menor;reparación de vehículos automotores y motocicletas"),
"49":("Transporte por vía terrestre y transporte por tuberías", "Transporte y almacenamiento"),
"50":("Transporte por vía acuática", "Transporte y almacenamiento"),
"51":("Transporte por vía aérea", "Transporte y almacenamiento"),
"52":("Almacenamiento y actividades de apoyo al transporte", "Transporte y almacenamiento"),
"53":("Actividades postales y de mensajería", "Transporte y almacenamiento"),
"55":("Actividades de alojamiento", "Actividades de alojamiento y de servicio de comidas"),
"56":("Actividades de servicio de comidas y bebidas", "Actividades de alojamiento y de servicio de comidas"),
"58":("Actividades de edición", "Información y comunicaciones"),
"59":("Actividades de producción de películas cinematográficas, vídeos y programas de televisión, grabación de sonido y edición de música", "Información y comunicaciones"),
"60":("Actividades de programación y transmisión", "Información y comunicaciones"),
"61":("Telecomunicaciones", "Información y comunicaciones"),
"62":("Programación informática, consultoría de informática y actividades conexas", "Información y comunicaciones"),
"63":("Actividades de servicios de información", "Información y comunicaciones"),
"64":("Actividades de servicios financieros, excepto las de seguros y fondos de pensiones", "Actividades financieras y de seguros"),
"65":("Seguros, reaseguros y fondos de pensiones, excepto planes de seguridad social de afiliación obligatoria", "Actividades financieras y de seguros"),
"66":("Actividades auxiliares de las actividades de servicios financieros", "Actividades financieras y de seguros"),
"68":("Actividades inmobiliarias", "Actividades inmobiliarias"),
"69":("Actividades jurídicas y de contabilidad", "Actividades profesionales, científicas y técnicas"),
"70":("Actividades de oficinas principales; actividades de consultoría de gestión", "Actividades profesionales, científicas y técnicas"),
"71":("Actividades de arquitectura e ingeniería; ensayos y análisis técnicos", "Actividades profesionales, científicas y técnicas"),
"72":("Investigación científica y desarrollo", "Actividades profesionales, científicas y técnicas"),
"73":("Publicidad y estudios de mercado", "Actividades profesionales, científicas y técnicas"),
"74":("Otras actividades profesionales, científicas y técnicas", "Actividades profesionales, científicas y técnicas"),
"75":("Actividades veterinarias", "Actividades profesionales, científicas y técnicas"),
"77":("Actividades de alquiler y arrendamiento", "Actividades de servicios administrativos y de apoyo"),
"78":("Actividades de empleo", "Actividades de servicios administrativos y de apoyo"),
"79":("Actividades de agencias de viajes y operadores turísticos y servicios de reservas y actividades conexas", "Actividades de servicios administrativos y de apoyo"),
"80":("Actividades de seguridad e investigación", "Actividades de servicios administrativos y de apoyo"),
"81":("Actividades de servicios a edificios y de paisajismo", "Actividades de servicios administrativos y de apoyo"),
"82":("Actividades administrativas y de apoyo de oficina y otras actividades de apoyo a las empresas", "Actividades de servicios administrativos y de apoyo"),
"84":("Administración pública y defensa; planes de seguridad social de afiliación obligatoria", "Administración pública y defensa; planes de seguridad social de afiliación obligatoria"),
"85":("Enseñanza", "Enseñanza"),
"86":("Actividades de atención de la salud humana", "Actividades de atención de la salud humana y de asistencia social"),
"87":("Actividades de atención en instituciones", "Actividades de atención de la salud humana y de asistencia social"),
"88":("Actividades de asistencia social sin alojamiento", "Actividades de atención de la salud humana y de asistencia social"),
"90":("Actividades creativas, artísticas y de entretenimiento", "Actividades artísticas, de entretenimiento y recreativas"),
"91":("Actividades de bibliotecas, archivos y museos y otras actividades culturales", "Actividades artísticas, de entretenimiento y recreativas"),
"92":("Actividades de juegos de azar y apuestas", "Actividades artísticas, de entretenimiento y recreativas"),
"93":("Actividades deportivas, de esparcimiento y recreativas", "Actividades artísticas, de entretenimiento y recreativas"),
"94":("Actividades de asociaciones", "Otras actividades de servicios"),
"95":("Reparación de ordenadores y de efectos personales y enseres domésticos", "Otras actividades de servicios"),
"96":("Otras actividades de servicios personales", "Otras actividades de servicios"),
"97":("Actividades de los hogares como empleadores de personal doméstico", "Actividades de los hogares como empleadores; actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio"),
"98":("Actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio", "Actividades de los hogares como empleadores; actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio"),
"99":("Actividades de organizaciones y órganos extraterritoriales", "Actividades de organizaciones y órganos extraterritoriales")
}
# https://unstats.un.org/unsd/publication/seriesm/seriesm_4rev4s.pdf